### ISSUE TITLE
Overflow on series page

### ISSUE THREAD

**Issue by ddamato** [codetv-dev/codetv.dev#8]
A horizontal scrollbar exists (using Windows and Microsoft Edge) due to the `.video-wrapper` element having an `inline-size` of `100dvi`. Changing this to `inline-size: 100%` will fix this issue. I'll also recommend removing the `min-block-size` setting here, as this creates black bars at the top and bottom of the element on small viewports.

In fact, you could actually remove much of the CSS happening here to get the same effect:

```css
.video-wrapper {
  background: var(--gray-900);
  border-bottom: 1px solid var(--gray-600);
}

lite-youtube {
  margin-inline: auto;
  aspect-ratio: 16 / 9;
}
```

You might be able to get rid of the `aspect-ratio` in there too depending on if there's nothing you need to force into that ratio.
